services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    #Expose  for me to can see database from outside docker
    ports:
      - "3309:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]

  app:
    build: .
    container_name: todo-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todo-app-network


volumes:
  mysql-data:
    driver: local

networks:
  todo-app-network:
    driver: bridge